#每1点经验值需要多少游戏币
exprate:
#是否开启权限节点，如关闭将只有0生效
  #如只需要个别只需将不需要的设置为0
  enable: true
  level:
    0: 10
    1: 8
    2: 6
    3: 4
    4: 2
    5: 1
deathkeep:
  keepworld: 50
  keepother: 100
  minDropWorld: 3
  maxDropWorld: 5
  minDropOther: 5
  maxDropOther: 10